-- Create Enum for Hipodromos if it doesn't exist (or use text check constraint)
-- For simplicity and robustness with Supabase which sometimes has issues with Enums in migrations depending on existing types, 
-- we will use a Text column with a Check constraint, or create the type if we are sure.
-- Let's check for type existence first to be safe, or just use 'text' with constraint.
-- Using 'text' with CHECK constraint is often easier to manage than custom ENUM types in raw SQL migrations unless managed by an ORM.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'hipodromo_enum') THEN
        create type hipodromo_enum as enum ('CHS', 'HCH', 'VSC', 'CHC');
    END IF;
END $$;

create table if not exists public.pozos_alertas (
    id bigint generated by default as identity primary key,
    hipodromo hipodromo_enum not null,
    fecha_evento date not null,
    nro_carrera integer not null,
    tipo_apuesta text not null, -- e.g., 'Triple', 'Superfecta'
    monto_estimado integer not null,
    mensaje_marketing text, -- e.g., '¡Pozo Garantizado!'
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add comment for documentation
comment on table public.pozos_alertas is 'Tabla para almacenar alertas de pozos millonarios scrapeados de los hipódromos.';

-- Enable RLS
alter table public.pozos_alertas enable row level security;

-- Policy: Public Read Access (Anyone can see the jackpots)
-- Policy: Public Read Access (Anyone can see the jackpots)
-- We drop it first to ensure we apply the latest definition and avoid "already exists" errors.
drop policy if exists "Pozos are public viewable" on public.pozos_alertas;

create policy "Pozos are public viewable"
  on public.pozos_alertas
  for select
  using ( true );

-- Policy: Service Role Write Access (Only the backend scraper script can insert/update)
-- In Supabase, the "service_role" key bypasses RLS, but it's good practice to have explicit policies or default deny.
-- Default is deny for roles that don't match a policy. 
-- We can explicitly allow the authenticated role if we had an admin panel, 
-- but for a backend script using the service key, RLS is bypassed. 
-- However, if we want to be strict for functionality that might use a limited role:
-- (No specific policy needed for service_role as it bypasses RLS, but we ensure no ONE ELSE can write)

-- If we wanted to allow an 'admin' user to write:
-- create policy "Admins can insert pozos"
--   on public.pozos_alertas
--   for insert
--   with check ( auth.role() = 'service_role' ); -- This is redundant as service_role bypasses, but good for clarity if using other roles.

-- Indexes for frequent queries (filtering by date and hipodromo)
create index if not exists pozos_alertas_fecha_idx on public.pozos_alertas (fecha_evento);
create index if not exists pozos_alertas_hipodromo_idx on public.pozos_alertas (hipodromo);
